#!/usr/bin/env python3
"""
visualize_report.py

Visualize the JSON report generated by compare_csv_folders.py
Supports both console and HTML output formats.

Examples:
  python -m src.visualize_report report.json
  python -m src.visualize_report report.json --format html --output report.html
"""

import argparse
import json
from pathlib import Path
from typing import Dict, List, Any


def format_console_report(data: Dict[str, Any]) -> str:
    """Format the report for console output with colors and structure."""
    output = []
    summary = data.get("summary", {})
    reports = data.get("reports", [])
    
    # Header
    output.append("=" * 80)
    output.append("CSV COMPARISON REPORT")
    output.append("=" * 80)
    output.append("")
    
    # Summary Section
    output.append("SUMMARY")
    output.append("-" * 80)
    output.append(f"Folder A: {summary.get('folder_a', 'N/A')}")
    output.append(f"Folder B: {summary.get('folder_b', 'N/A')}")
    output.append(f"Total files in A: {summary.get('total_files_in_a', 0)}")
    output.append(f"Total files in B: {summary.get('total_files_in_b', 0)}")
    output.append(f"Files compared: {summary.get('files_compared', 0)}")
    output.append(f"Files only in A: {summary.get('files_only_in_a', 0)}")
    output.append(f"Files only in B: {summary.get('files_only_in_b', 0)}")
    output.append(f"Files in both: {summary.get('files_in_both', 0)}")
    output.append(f"Files with differences: {summary.get('files_with_differences', 0)}")
    output.append("")
    
    # Options
    options = summary.get("options", {})
    if options:
        output.append("Options:")
        for key, value in options.items():
            output.append(f"  {key}: {value}")
        output.append("")
    
    # Detailed Reports
    if reports:
        output.append("=" * 80)
        output.append("DETAILED DIFFERENCES")
        output.append("=" * 80)
        output.append("")
        
        for i, report in enumerate(reports, 1):
            output.append(f"\n[{i}] {report.get('filename', 'Unknown')}")
            output.append("-" * 80)
            
            # File existence
            if not report.get('exists_in_a', True):
                output.append("  ⚠ Missing in folder A")
                continue
            if not report.get('exists_in_b', True):
                output.append("  ⚠ Missing in folder B")
                continue
            
            # Error
            if report.get('error'):
                output.append(f"  ❌ ERROR: {report['error']}")
                continue
            
            # Structural info
            output.append(f"  Rows:    A={report.get('rows_a', 'N/A')}  B={report.get('rows_b', 'N/A')}")
            output.append(f"  Columns: A={report.get('cols_a', 'N/A')}  B={report.get('cols_b', 'N/A')}")
            
            # Header analysis
            if report.get('header_equal') is False:
                output.append("  ❌ Headers differ (set mismatch)")
                if report.get('header_only_in_a'):
                    output.append(f"     Only in A: {report['header_only_in_a']}")
                if report.get('header_only_in_b'):
                    output.append(f"     Only in B: {report['header_only_in_b']}")
            elif report.get('header_equal') is True:
                if report.get('header_order_equal'):
                    output.append("  ✓ Headers: same (including order)")
                else:
                    output.append("  ⚠ Headers: same set, different order")
            
            # Content comparison
            if report.get('content_equal') is not None:
                if report.get('content_equal'):
                    output.append("  ✓ Content: identical")
                else:
                    diff_count = report.get('differing_row_count', 0)
                    output.append(f"  ❌ Content: {diff_count} row(s) differ")
                    
                    # Sample differences
                    samples = report.get('sample_differences', [])
                    if samples:
                        output.append("\n  Sample Differences:")
                        for diff in samples:
                            if 'differing_fields' in diff:
                                idx_a = diff.get('row_index_a_1_based', '?')
                                idx_b = diff.get('row_index_b_1_based', '?')
                                fields = diff['differing_fields']
                                output.append(f"\n    Row A:{idx_a} vs B:{idx_b} - {len(fields)} field(s) differ:")
                                for field in fields:
                                    col_name = field.get('column_name', f"col_{field.get('column_index', '?')}")
                                    val_a = field.get('a', '')
                                    val_b = field.get('b', '')
                                    output.append(f"      • {col_name}:")
                                    output.append(f"          A: '{val_a}'")
                                    output.append(f"          B: '{val_b}'")
                            elif 'status' in diff:
                                status = diff['status']
                                row_data = diff.get('row', [])
                                if status == 'only_in_a':
                                    idx = diff.get('row_index_a_1_based', '?')
                                    output.append(f"\n    Row A:{idx} - Only in A")
                                elif status == 'only_in_b':
                                    idx = diff.get('row_index_b_1_based', '?')
                                    output.append(f"\n    Row B:{idx} - Only in B")
                                output.append(f"      Data: {row_data}")
    else:
        output.append("\n✓ No differences found!")
    
    output.append("\n" + "=" * 80)
    return "\n".join(output)


def format_html_report(data: Dict[str, Any]) -> str:
    """Format the report as an HTML page."""
    summary = data.get("summary", {})
    reports = data.get("reports", [])
    
    html = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CSV Comparison Report</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            max-width: 1400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 20px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }
        .header h1 {
            margin: 0 0 20px 0;
        }
        .summary {
            background: white;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 20px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .summary-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 15px;
            margin-top: 15px;
        }
        .stat-box {
            padding: 15px;
            background: #f8f9fa;
            border-radius: 6px;
            border-left: 4px solid #667eea;
        }
        .stat-label {
            font-size: 12px;
            color: #666;
            text-transform: uppercase;
            margin-bottom: 5px;
        }
        .stat-value {
            font-size: 24px;
            font-weight: bold;
            color: #333;
        }
        .file-report {
            background: white;
            padding: 20px;
            margin-bottom: 15px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .file-header {
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 15px;
            color: #333;
            border-bottom: 2px solid #667eea;
            padding-bottom: 10px;
        }
        .status {
            display: inline-block;
            padding: 4px 12px;
            border-radius: 12px;
            font-size: 12px;
            font-weight: bold;
            margin-left: 10px;
        }
        .status-ok { background: #d4edda; color: #155724; }
        .status-warning { background: #fff3cd; color: #856404; }
        .status-error { background: #f8d7da; color: #721c24; }
        .info-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 10px;
            margin: 15px 0;
            font-size: 14px;
        }
        .info-item {
            padding: 8px;
            background: #f8f9fa;
            border-radius: 4px;
        }
        .differences {
            margin-top: 20px;
        }
        .diff-item {
            background: #fff8e1;
            padding: 15px;
            margin: 10px 0;
            border-left: 4px solid #ffa726;
            border-radius: 4px;
        }
        .diff-header {
            font-weight: bold;
            margin-bottom: 10px;
            color: #e65100;
        }
        .field-diff {
            margin: 8px 0;
            padding: 10px;
            background: white;
            border-radius: 4px;
        }
        .field-name {
            font-weight: bold;
            color: #1976d2;
            margin-bottom: 5px;
        }
        .value-comparison {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 10px;
            margin-top: 5px;
        }
        .value-box {
            padding: 8px;
            border-radius: 4px;
            font-family: 'Courier New', monospace;
            font-size: 13px;
        }
        .value-a { background: #ffebee; border-left: 3px solid #e53935; }
        .value-b { background: #e3f2fd; border-left: 3px solid #1e88e5; }
        .label { font-size: 11px; color: #666; margin-bottom: 3px; }
        .options {
            background: #e8eaf6;
            padding: 15px;
            border-radius: 6px;
            margin-top: 15px;
        }
        .options-title {
            font-weight: bold;
            margin-bottom: 10px;
            color: #3f51b5;
        }
        .options-list {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
            gap: 8px;
            font-size: 13px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>📊 CSV Comparison Report</h1>
"""
    
    # Summary stats
    html += """
    </div>
    <div class="summary">
        <h2>Summary</h2>
        <div class="summary-grid">
"""
    
    stats = [
        ("Total Files in A", summary.get('total_files_in_a', 0)),
        ("Total Files in B", summary.get('total_files_in_b', 0)),
        ("Files Compared", summary.get('files_compared', 0)),
        ("Only in A", summary.get('files_only_in_a', 0)),
        ("Only in B", summary.get('files_only_in_b', 0)),
        ("Files with Differences", summary.get('files_with_differences', 0)),
    ]
    
    for label, value in stats:
        html += f"""
            <div class="stat-box">
                <div class="stat-label">{label}</div>
                <div class="stat-value">{value}</div>
            </div>
"""
    
    html += """
        </div>
"""
    
    # Options
    options = summary.get('options', {})
    if options:
        html += """
        <div class="options">
            <div class="options-title">Comparison Options</div>
            <div class="options-list">
"""
        for key, value in options.items():
            html += f"                <div>• {key}: <strong>{value}</strong></div>\n"
        html += """
            </div>
        </div>
"""
    
    html += """
    </div>
"""
    
    # Detailed reports
    if reports:
        html += """
    <h2>Detailed Differences</h2>
"""
        for report in reports:
            filename = report.get('filename', 'Unknown')
            
            # Determine status
            if not report.get('exists_in_a', True):
                status = '<span class="status status-error">Missing in A</span>'
            elif not report.get('exists_in_b', True):
                status = '<span class="status status-error">Missing in B</span>'
            elif report.get('error'):
                status = '<span class="status status-error">Error</span>'
            elif report.get('content_equal'):
                continue  # Skip identical files
            elif report.get('content_equal') is False:
                status = '<span class="status status-warning">Differences Found</span>'
            else:
                status = '<span class="status status-ok">OK</span>'
            
            html += f"""
    <div class="file-report">
        <div class="file-header">
            {filename}
            {status}
        </div>
"""
            
            if report.get('error'):
                html += f'        <div class="status-error">Error: {report["error"]}</div>\n'
            else:
                # Info grid
                html += """
        <div class="info-grid">
"""
                html += f'            <div class="info-item">Rows A: <strong>{report.get("rows_a", "N/A")}</strong></div>\n'
                html += f'            <div class="info-item">Rows B: <strong>{report.get("rows_b", "N/A")}</strong></div>\n'
                html += f'            <div class="info-item">Columns A: <strong>{report.get("cols_a", "N/A")}</strong></div>\n'
                html += f'            <div class="info-item">Columns B: <strong>{report.get("cols_b", "N/A")}</strong></div>\n'
                html += """
        </div>
"""
                
                # Sample differences
                samples = report.get('sample_differences', [])
                if samples:
                    html += """
        <div class="differences">
            <h3>Differences:</h3>
"""
                    for diff in samples:
                        if 'differing_fields' in diff:
                            idx_a = diff.get('row_index_a_1_based', '?')
                            idx_b = diff.get('row_index_b_1_based', '?')
                            fields = diff['differing_fields']
                            
                            html += f"""
            <div class="diff-item">
                <div class="diff-header">Row A:{idx_a} vs B:{idx_b} — {len(fields)} field(s) differ</div>
"""
                            for field in fields:
                                col_name = field.get('column_name', f"col_{field.get('column_index', '?')}")
                                val_a = field.get('a', '')
                                val_b = field.get('b', '')
                                
                                html += f"""
                <div class="field-diff">
                    <div class="field-name">{col_name}</div>
                    <div class="value-comparison">
                        <div class="value-box value-a">
                            <div class="label">File A:</div>
                            {val_a}
                        </div>
                        <div class="value-box value-b">
                            <div class="label">File B:</div>
                            {val_b}
                        </div>
                    </div>
                </div>
"""
                            html += """
            </div>
"""
                        elif 'status' in diff:
                            status = diff['status']
                            if status == 'only_in_a':
                                idx = diff.get('row_index_a_1_based', '?')
                                html += f'            <div class="diff-item"><div class="diff-header">Row A:{idx} - Only in A</div></div>\n'
                            elif status == 'only_in_b':
                                idx = diff.get('row_index_b_1_based', '?')
                                html += f'            <div class="diff-item"><div class="diff-header">Row B:{idx} - Only in B</div></div>\n'
                    
                    html += """
        </div>
"""
            
            html += """
    </div>
"""
    else:
        html += """
    <div class="file-report">
        <div style="text-align: center; color: #4caf50; font-size: 24px; padding: 40px;">
            ✓ No differences found!
        </div>
    </div>
"""
    
    html += """
</body>
</html>
"""
    return html


def main() -> int:
    ap = argparse.ArgumentParser(description="Visualize CSV comparison report")
    ap.add_argument("report", type=str, help="Path to report.json file")
    ap.add_argument("--format", choices=["console", "html"], default="console",
                    help="Output format (default: console)")
    ap.add_argument("--output", type=str, help="Output file path (for HTML format)")
    
    args = ap.parse_args()
    
    report_path = Path(args.report).expanduser().resolve()
    
    if not report_path.exists():
        print(f"Error: Report file not found: {report_path}")
        return 1
    
    try:
        with report_path.open("r", encoding="utf-8") as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON in report file: {e}")
        return 1
    except Exception as e:
        print(f"Error reading report file: {e}")
        return 1
    
    if args.format == "console":
        output = format_console_report(data)
        print(output)
    elif args.format == "html":
        output = format_html_report(data)
        
        if args.output:
            output_path = Path(args.output).expanduser().resolve()
            output_path.parent.mkdir(parents=True, exist_ok=True)
            with output_path.open("w", encoding="utf-8") as f:
                f.write(output)
            print(f"HTML report written to: {output_path}")
        else:
            print(output)
    
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
